### ISSUE TITLE
circular import issue

### ISSUE THREAD

**Issue by kilink** [gawel/webtest-selenium#9]
I can't seem to run the tests due to a circular import between WebTest and webtest-selenium.  webtest-selenium tries to import webtest.app, but webtest.**init** tries to import webtest_selenium.SeleniumApp.

How should I be running the tests?

**Comment by gawel** [comment]
Imports removed from webtest. https://github.com/Pylons/webtest/commit/dcfae9d18833a04f9b7d742fb7d7c6f26eee2923
